spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}?currentSchema=public
        username: ${POSTGRES_USER:dbuser}
        password: ${POSTGRES_PASSWORD:pass}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:db/changelog-master.xml
        contexts: test
        test-rollback-on-update: true
